version: "3.6"

volumes:
  mysql:
  vcash:

services:
  victoryslot:
    build: .
    ports:
      - "80:80"

  vcashd:
    expose:
      - 9195
    image: yangm97/vcashd-docker
    ports:
      - "9195:9195"
    volumes:
      - vcash:/home/.Vcash

  mysql:
    image: mysql:8
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: VictorySlotDb
      MYSQL_PASSWORD: VictorySlotPw
    volumes:
      - mysql:/var/lib/mysql
      - ./db/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
