CREATE DATABASE IF NOT EXISTS `victoryslotdb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `victoryslotdb`;

CREATE TABLE IF NOT EXISTS bet (
id INTEGER AUTO_INCREMENT PRIMARY KEY,
house_address CHAR(50) NOT NULL,
user_address CHAR(50),
amount DOUBLE,
created DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL,
updated DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
status INTEGER DEFAULT 0,
score INTEGER DEFAULT 0,
reward DOUBLE DEFAULT 0,
refund DOUBLE DEFAULT 0,
game INTEGER DEFAULT 0,
currency INTEGER DEFAULT 0,
details TEXT,
INDEX(house_address)) ENGINE=InnoDB;